### ISSUE TITLE
Build failed: Missing root project?

### ISSUE THREAD

**Issue by ghost** [tompreuss/APNSettings#1]
A clean checkout of the repo does not build, just clone it and even `gradle clean` doesn't run. Form the first look, the repo is missing the root project. Your structure most likely looks like this...
- apnsettings
  - build.gradle
  - ...
  - app
    - build.gradle
    - src
    - ...

... but you only added the app folder to git.

**Comment by tompreuss** [comment]
Okay, I've believe I have everything in the repo in the proper place now, thanks to your help.  I've replied to you [on gitlab](https://gitlab.com/fdroid/fdroiddata/merge_requests/532#note_821861) as well, and I'll mark this closed since a fresh clone and `gradle clean` now works.

Thanks again!
